[package]
name = "wavefncollapse"
edition = "2021"
version = "0.1.0"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive"] }
log = "0.4.17"
pretty_env_logger = "0.4.0"
pretty_logger = "0.1.8"
rand = "0.8.5"

[dev-dependencies]
pretty_assertions = "1.3.0"


